In [1]:
import tensorflow as tf

# Simulate 10 throwings of one die and one coin.

In [7]:
coin_flip = tf.random.uniform([10, 1], maxval=2, dtype=tf.int32)

In [8]:
coin_flip

<tf.Tensor: id=11, shape=(10, 1), dtype=int32, numpy=
array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1]], dtype=int32)>

In [13]:
die_roll = tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32)
die_roll

<tf.Tensor: id=31, shape=(10, 1), dtype=int32, numpy=
array([[5],
       [4],
       [3],
       [5],
       [4],
       [5],
       [3],
       [3],
       [5],
       [6]], dtype=int32)>

In [15]:
die_is_bigger_than = tf.cast(tf.math.greater(die_roll, 3), tf.int32)
die_is_bigger_than

<tf.Tensor: id=36, shape=(10, 1), dtype=int32, numpy=
array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1]], dtype=int32)>

In [18]:
success = tf.cast(tf.math.equal(die_is_bigger_than + coin_flip, 2), tf.int32)
success

<tf.Tensor: id=47, shape=(10, 1), dtype=int32, numpy=
array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int32)>

In [19]:
simulation_result = tf.concat([coin_flip, die_roll, success], axis=1)
simulation_result

<tf.Tensor: id=49, shape=(10, 3), dtype=int32, numpy=
array([[1, 5, 1],
       [0, 4, 0],
       [1, 3, 0],
       [0, 5, 0],
       [1, 4, 1],
       [0, 5, 0],
       [1, 3, 0],
       [0, 3, 0],
       [0, 5, 0],
       [1, 6, 1]], dtype=int32)>

# Normalized Euclidean Distance

In [36]:
v = tf.random.uniform([3, 5], maxval=2, dtype=tf.int32) 
w = tf.random.uniform([2, 5], maxval=2, dtype=tf.int32)

In [40]:
v,w

(<tf.Tensor: id=104, shape=(3, 5), dtype=int32, numpy=
 array([[1, 1, 1, 1, 0],
        [1, 1, 0, 0, 1],
        [1, 0, 1, 0, 0]], dtype=int32)>,
 <tf.Tensor: id=108, shape=(2, 5), dtype=int32, numpy=
 array([[1, 0, 0, 0, 1],
        [0, 0, 1, 0, 0]], dtype=int32)>)

In [37]:
n = tf.shape(v)[0]
m = tf.shape(w)[0]

In [38]:
m

<tf.Tensor: id=118, shape=(), dtype=int32, numpy=2>

In [41]:
tf.expand_dims(v, 1)

<tf.Tensor: id=122, shape=(3, 1, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 0]],

       [[1, 1, 0, 0, 1]],

       [[1, 0, 1, 0, 0]]], dtype=int32)>

In [42]:
tf.tile(tf.expand_dims(v, 1), [1, m, 1])

<tf.Tensor: id=128, shape=(3, 2, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 0],
        [1, 1, 1, 1, 0]],

       [[1, 1, 0, 0, 1],
        [1, 1, 0, 0, 1]],

       [[1, 0, 1, 0, 0],
        [1, 0, 1, 0, 0]]], dtype=int32)>