# In numpy

In [10]:
import operator
import numpy as np
from functools import reduce
 
def mask_size_helper(args):
    # multiply n dimensions to get array size
    return reduce(operator.mul, args) 
 
def create_dropconnect_mask(dc_keep_prob, dimensions):
    # get binary mask of size=*dimensions from binomial dist. with dc_keep_prob = prob of drawing a 1
    mask_vector = np.random.binomial(1, dc_keep_prob, mask_size_helper(dimensions))
    # reshape mask to correct dimensions (we could just broadcast, but that's messy)
    mask_array = mask_vector.reshape(dimensions)
    return mask_array
 
def dropconnect(W, dc_keep_prob):
    dimensions = W.shape
    return W * create_dropconnect_mask(dc_keep_prob, dimensions)

In [18]:
W = np.random.rand(2,5)
W

array([[0.43142942, 0.59333534, 0.49498051, 0.04962081, 0.52335115],
       [0.66864335, 0.2555287 , 0.65147986, 0.94848729, 0.77101737]])

In [24]:
dc_keep_prob = 0.8
dropconnect(W, dc_keep_prob)

array([[0.43142942, 0.        , 0.49498051, 0.        , 0.52335115],
       [0.66864335, 0.        , 0.65147986, 0.94848729, 0.        ]])

# In Tensorflow

In [40]:
import tensorflow as tf
def dropconnect(W, p):
    return tf.nn.dropout(W, rate=p) * p

In [64]:
W = np.random.rand(2,5)
p = 0.2
dropconnect(W, p)

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[0.14998233, 0.19069256, 0.04083121, 0.        , 0.20048243],
       [0.14011639, 0.24706913, 0.14806555, 0.24796889, 0.15302356]])>