In [1]:
import tensorflow as tf
import tensorflow_hub as hub
from transformers import BertTokenizer
import transformers

In [2]:
transformers.__version__

'2.3.0'

In [49]:
tokenizer = BertTokenizer.from_pretrained("/Users/ankur.kumar/Downloads/bert_large_uncased_vocab.txt")

In [50]:
tokenizer.vocab

OrderedDict([('[PAD]', 0),
             ('[unused0]', 1),
             ('[unused1]', 2),
             ('[unused2]', 3),
             ('[unused3]', 4),
             ('[unused4]', 5),
             ('[unused5]', 6),
             ('[unused6]', 7),
             ('[unused7]', 8),
             ('[unused8]', 9),
             ('[unused9]', 10),
             ('[unused10]', 11),
             ('[unused11]', 12),
             ('[unused12]', 13),
             ('[unused13]', 14),
             ('[unused14]', 15),
             ('[unused15]', 16),
             ('[unused16]', 17),
             ('[unused17]', 18),
             ('[unused18]', 19),
             ('[unused19]', 20),
             ('[unused20]', 21),
             ('[unused21]', 22),
             ('[unused22]', 23),
             ('[unused23]', 24),
             ('[unused24]', 25),
             ('[unused25]', 26),
             ('[unused26]', 27),
             ('[unused27]', 28),
             ('[unused28]', 29),
             ('[unused29]', 30),
  

In [53]:
tokenizer.tokenize("I [p1] H1p ppp <h1>")

['i',
 '[',
 'p',
 '##1',
 ']',
 'h',
 '##1',
 '##p',
 'pp',
 '##p',
 '<',
 'h',
 '##1',
 '>']

In [47]:
tokenizer.add_tokens(['<p>','H1p','ppp','<H1>'])

3

In [48]:
tokenizer.tokenize("I <p> H1p ppp <H1>")

['i', '<', 'p', '>', 'H1p', 'ppp', '<H1>']

In [38]:
tokenizer.vocab_size

30522

In [6]:
#model = hub.load("/Users/ankur.kumar/Downloads/1")

In [7]:
def get_add_tokens(do_enumerate):
    tags = ['Dd', 'Dl', 'Dt', 'H1', 'H2', 'H3', 'Li', 'Ol', 'P', 'Table', 'Td', 'Th', 'Tr', 'Ul']
    opening_tags = [f'<{tag}>' for tag in tags]
    closing_tags = [f'</{tag}>' for tag in tags]
    added_tags = opening_tags + closing_tags
    # See `nq_to_sqaud.py` for special-tokens
    special_tokens = ['<P>', '<Table>']
    if do_enumerate:
        for special_token in special_tokens:
            for j in range(11):
              added_tags.append(f'<{special_token[1: -1]}{j}>')

    add_tokens = ['Td_colspan', 'Th_colspan', '``', '\'\'', '--']
    add_tokens = add_tokens + added_tags
    return add_tokens

tags = get_add_tokens(True)

In [8]:
tags = [x.lower() for x in tags]

In [8]:
len(tags)

55

In [10]:
tokenizer.tokenize("<p> Hi I am Ankur")

['<', 'p', '>', 'hi', 'i', 'am', 'an', '##kur']

In [11]:
tokenizer.tokenize("<p> Hi I am Ankur")

['<', 'p', '>', 'hi', 'i', 'am', 'an', '##kur']

In [3]:
questions = [
    'How long did it take to find the answer?',
    'What\'s the answer to the great question?',
    'What\'s the name of the computer?']
paragraph = '''<p>The computer is named Deep Thought.</p>.
               <p>After 46 million years of training it found the answer.</p>
               <p>However, nobody was amazed. The answer was 42.</p>'''

In [4]:
question = questions[0]

question_tokens = tokenizer.tokenize(question)
paragraph_tokens = tokenizer.tokenize(paragraph)

In [5]:
question_tokens

['how', 'long', 'did', 'it', 'take', 'to', 'find', 'the', 'answer', '?']

In [6]:
paragraph_tokens

['<',
 'p',
 '>',
 'the',
 'computer',
 'is',
 'named',
 'deep',
 'thought',
 '.',
 '<',
 '/',
 'p',
 '>',
 '.',
 '<',
 'p',
 '>',
 'after',
 '46',
 'million',
 'years',
 'of',
 'training',
 'it',
 'found',
 'the',
 'answer',
 '.',
 '<',
 '/',
 'p',
 '>',
 '<',
 'p',
 '>',
 'however',
 ',',
 'nobody',
 'was',
 'amazed',
 '.',
 'the',
 'answer',
 'was',
 '42',
 '.',
 '<',
 '/',
 'p',
 '>']

In [41]:
tokens = ['[CLS]'] + question_tokens + ['[SEP]'] + paragraph_tokens + ['[SEP]']

In [42]:
input_word_ids = tokenizer.convert_tokens_to_ids(tokens)
input_mask = [1] * len(input_word_ids)
input_type_ids = [0] * (1 + len(question_tokens) + 1) + [1] * (len(paragraph_tokens) + 1)

In [43]:
input_word_ids, input_mask, input_type_ids = map(lambda t: tf.expand_dims(
      tf.convert_to_tensor(t, dtype=tf.int32), 0), (input_word_ids, input_mask, input_type_ids))

In [45]:
input_word_ids, input_mask, input_type_ids

(<tf.Tensor: id=89185, shape=(1, 49), dtype=int32, numpy=
 array([[  101,  2129,  2146,  2106,  2009,  2202,  2000,  2424,  1996,
          3437,  1029,   102, 30535,  1996,  3274,  2003,  2315,  2784,
          2245,  1012, 30549,  1012, 30535,  2044,  4805,  2454,  2086,
          1997,  2731,  2009,  2179,  1996,  3437,  1012, 30549, 30535,
          2174,  1010,  6343,  2001, 15261,  1012,  1996,  3437,  2001,
          4413,  1012, 30549,   102]], dtype=int32)>,
 <tf.Tensor: id=89188, shape=(1, 49), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1]], dtype=int32)>,
 <tf.Tensor: id=89191, shape=(1, 49), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1]], dtype=int32)>)

In [46]:
outputs = model([input_word_ids, input_mask, input_type_ids])

InvalidArgumentError:  indices[0,12] = 30535 is not in [0, 30522)
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/tf_bert_for_natural_question_answering/StatefulPartitionedCall/bert/StatefulPartitionedCall/embeddings/Gather}}]] [Op:__inference_restored_function_body_89598]

Function call stack:
restored_function_body
